/**
 * TeacherReport Entity
 *
 * Represents metadata of reports generated by teachers.
 * Maps to: social_features.teacher_reports
 *
 * @see apps/database/ddl/schemas/social_features/tables/08-teacher_reports.sql
 */

import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { DB_SCHEMAS, DB_TABLES } from '@/shared/constants/database.constants';
import {
  TeacherReportTypeEnum,
  TeacherReportFormatEnum,
} from '@/shared/constants/enums.constants';
import { Profile } from '../../auth/entities/profile.entity';
import { Tenant } from '../../auth/entities/tenant.entity';
import { Classroom } from '../../social/entities/classroom.entity';

/**
 * Entity for teacher-generated reports metadata
 */
@Entity({ name: DB_TABLES.SOCIAL.TEACHER_REPORTS, schema: DB_SCHEMAS.SOCIAL })
export class TeacherReport {
  @PrimaryGeneratedColumn('uuid')
    id!: string;

  @Column({ name: 'teacher_id', type: 'uuid' })
    teacherId!: string;

  /**
   * Relación Many-to-One con Profile (teacher)
   * FIX-2026-01-19: Agregada relación faltante para coherencia DDL-Backend
   */
  @ManyToOne(() => Profile, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'teacher_id' })
    teacher?: Profile;

  @Column({ name: 'classroom_id', type: 'uuid', nullable: true })
    classroomId!: string | null;

  /**
   * Relación Many-to-One con Classroom (opcional)
   * FIX-2026-01-19: Agregada relación faltante para coherencia DDL-Backend
   */
  @ManyToOne(() => Classroom, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'classroom_id' })
    classroom?: Classroom | null;

  @Column({ name: 'tenant_id', type: 'uuid' })
    tenantId!: string;

  /**
   * Relación Many-to-One con Tenant
   * FIX-2026-01-19: Agregada relación faltante para coherencia DDL-Backend
   */
  @ManyToOne(() => Tenant, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'tenant_id' })
    tenant?: Tenant;

  @Column({ name: 'report_name', length: 255 })
    reportName!: string;

  /**
   * Tipo de reporte
   * FIX-2026-01-19: Tipado con enum para coherencia con CHECK constraint
   */
  @Column({ name: 'report_type', length: 50 })
    reportType!: TeacherReportTypeEnum;

  /**
   * Formato de exportación
   * FIX-2026-01-19: Tipado con enum para coherencia con CHECK constraint
   */
  @Column({ name: 'report_format', length: 10 })
    reportFormat!: TeacherReportFormatEnum;

  @Column({ name: 'student_count', type: 'int', default: 0 })
    studentCount!: number;

  @Column({ name: 'period_start', type: 'date', nullable: true })
    periodStart!: Date | null;

  @Column({ name: 'period_end', type: 'date', nullable: true })
    periodEnd!: Date | null;

  @Column({ name: 'file_path', type: 'text', nullable: true })
    filePath!: string | null;

  @Column({ name: 'file_size_bytes', type: 'bigint', nullable: true })
    fileSizeBytes!: number | null;

  @Column({ name: 'generated_at', type: 'timestamptz', default: () => 'NOW()' })
    generatedAt!: Date;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
    createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
    updatedAt!: Date;
}
