/**
 * Teacher Reports API Service
 *
 * Provides methods to generate, list, and download teacher reports
 * including PDF and Excel formats with student insights.
 *
 * All endpoints are prefixed with `/teacher/reports` and require
 * authentication with admin_teacher or super_admin role.
 *
 * @module services/api/teacher/reportsApi
 */

import { apiClient } from '../apiClient';

// ============================================================================
// TYPES
// ============================================================================

/**
 * Report formats available
 */
export type ReportFormat = 'pdf' | 'excel';

/**
 * Report types available
 */
export type ReportType =
  | 'users'
  | 'progress'
  | 'gamification'
  | 'system'
  | 'student_insights'
  | 'classroom_summary'
  | 'risk_analysis';

/**
 * DTO for generating a new report
 */
export interface GenerateReportDto {
  type: ReportType;
  format: ReportFormat;
  classroom_id?: string;
  student_ids?: string[];
  start_date?: string;
  end_date?: string;
}

/**
 * Metadata returned after report generation
 */
export interface ReportMetadata {
  report_id: string;
  type: ReportType;
  format: ReportFormat;
  generated_at: string;
  generated_by: string;
  student_count: number;
  file_size: number;
}

/**
 * Report record from database
 */
export interface TeacherReport {
  id: string;
  teacherId: string;
  tenantId: string;
  reportName: string;
  reportType: ReportType;
  reportFormat: 'pdf' | 'excel' | 'csv';
  classroomId?: string;
  studentCount: number;
  periodStart?: string;
  periodEnd?: string;
  filePath?: string;
  fileSizeBytes?: number;
  generatedAt: string;
  createdAt: string;
}

/**
 * Report statistics
 */
export interface ReportStats {
  total_reports: number;
  pdf_reports: number;
  excel_reports: number;
  total_students_analyzed: number;
  reports_this_month: number;
  last_report_date?: string;
}

// ============================================================================
// API FUNCTIONS
// ============================================================================

/**
 * Generate a new insights report
 *
 * @description Generates a comprehensive report with student insights in PDF or Excel format.
 * Reports include risk analysis, recommendations, strengths/weaknesses, and predictions.
 * The report is persisted to storage and metadata is saved to the database.
 *
 * @param dto - Report generation options
 * @returns Promise<Blob> - The generated report file
 *
 * @example
 * ```typescript
 * const blob = await reportsApi.generateReport({
 *   type: 'student_insights',
 *   format: 'pdf',
 *   classroom_id: 'classroom-uuid'
 * });
 *
 * // Download the file
 * const url = URL.createObjectURL(blob);
 * const a = document.createElement('a');
 * a.href = url;
 * a.download = 'student-insights.pdf';
 * a.click();
 * ```
 */
export async function generateReport(dto: GenerateReportDto): Promise<{
  blob: Blob;
  metadata: {
    reportId: string;
    studentCount: number;
    generatedAt: string;
  };
}> {
  try {
    const response = await apiClient.post('/teacher/reports/generate', dto, {
      responseType: 'blob',
    });

    // Extract metadata from headers
    const metadata = {
      reportId: response.headers['x-report-id'] || '',
      studentCount: parseInt(response.headers['x-student-count'] || '0', 10),
      generatedAt: response.headers['x-generated-at'] || new Date().toISOString(),
    };

    return {
      blob: response.data,
      metadata,
    };
  } catch (error) {
    console.error('[ReportsAPI] Error generating report:', error);
    throw error;
  }
}

/**
 * Get list of recent reports
 *
 * @description Retrieve a list of recent reports generated by the teacher.
 * Results are ordered by generation date (most recent first).
 *
 * @param limit - Maximum number of reports to return (default: 10)
 * @returns Promise<TeacherReport[]> - List of recent reports
 *
 * @example
 * ```typescript
 * const reports = await reportsApi.getRecentReports(5);
 * reports.forEach(report => {
 *   console.log(`${report.reportName} - ${report.studentCount} students`);
 * });
 * ```
 */
export async function getRecentReports(limit: number = 10): Promise<TeacherReport[]> {
  try {
    const { data } = await apiClient.get<TeacherReport[]>('/teacher/reports/recent', {
      params: { limit },
    });
    return data;
  } catch (error) {
    console.error('[ReportsAPI] Error fetching recent reports:', error);
    throw error;
  }
}

/**
 * Get report statistics
 *
 * @description Retrieve statistics about reports generated by the teacher
 * including total counts, format breakdown, and students analyzed.
 *
 * @returns Promise<ReportStats> - Report statistics
 *
 * @example
 * ```typescript
 * const stats = await reportsApi.getReportStats();
 * console.log(`Total reports: ${stats.total_reports}`);
 * console.log(`Students analyzed: ${stats.total_students_analyzed}`);
 * ```
 */
export async function getReportStats(): Promise<ReportStats> {
  try {
    const { data } = await apiClient.get<ReportStats>('/teacher/reports/stats');
    return data;
  } catch (error) {
    console.error('[ReportsAPI] Error fetching report stats:', error);
    throw error;
  }
}

/**
 * Download a previously generated report
 *
 * @description Download a report file. Validates teacher ownership.
 *
 * @param reportId - ID of the report to download
 * @returns Promise<Blob> - The report file
 *
 * @example
 * ```typescript
 * const blob = await reportsApi.downloadReport('report-uuid');
 *
 * // Create download link
 * const url = URL.createObjectURL(blob);
 * const a = document.createElement('a');
 * a.href = url;
 * a.download = 'report.pdf';
 * a.click();
 * ```
 */
export async function downloadReport(reportId: string): Promise<{
  blob: Blob;
  metadata: {
    reportId: string;
    teacherId: string;
    generatedAt: string;
    contentType: string;
  };
}> {
  try {
    const response = await apiClient.get(`/teacher/reports/${reportId}/download`, {
      responseType: 'blob',
    });

    const metadata = {
      reportId: response.headers['x-report-id'] || reportId,
      teacherId: response.headers['x-teacher-id'] || '',
      generatedAt: response.headers['x-generated-at'] || '',
      contentType: response.headers['content-type'] || 'application/octet-stream',
    };

    return {
      blob: response.data,
      metadata,
    };
  } catch (error) {
    console.error('[ReportsAPI] Error downloading report:', error);
    throw error;
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

/**
 * Reports API namespace
 *
 * @usage
 * ```typescript
 * import { reportsApi } from '@services/api/teacher/reportsApi';
 *
 * const result = await reportsApi.generateReport({ type: 'student_insights', format: 'pdf' });
 * const recent = await reportsApi.getRecentReports();
 * const stats = await reportsApi.getReportStats();
 * ```
 */
export const reportsApi = {
  generateReport,
  getRecentReports,
  getReportStats,
  downloadReport,
};

export default reportsApi;
