/**
 * Teacher Reports API Service
 *
 * Provides methods to generate, list, and download teacher reports
 * including PDF and Excel formats with student insights.
 *
 * All endpoints are prefixed with `/teacher/reports` and require
 * authentication with admin_teacher or super_admin role.
 *
 * @module services/api/teacher/reportsApi
 */

import { apiClient } from '../apiClient';

// ============================================================================
// TYPES
// ============================================================================

/**
 * Report formats available
 * TASK-2026-01-18-015 Sprint 4.3: Added 'csv' format support
 */
export type ReportFormat = 'pdf' | 'excel' | 'csv';

/**
 * Report types available
 */
export type ReportType =
  | 'users'
  | 'progress'
  | 'gamification'
  | 'system'
  | 'student_insights'
  | 'classroom_summary'
  | 'risk_analysis';

/**
 * DTO for generating a new report
 */
export interface GenerateReportDto {
  type: ReportType;
  format: ReportFormat;
  classroom_id?: string;
  student_ids?: string[];
  start_date?: string;
  end_date?: string;
}

/**
 * Metadata returned after report generation
 */
export interface ReportMetadata {
  report_id: string;
  type: ReportType;
  format: ReportFormat;
  generated_at: string;
  generated_by: string;
  student_count: number;
  file_size: number;
}

/**
 * Report metadata from backend API (snake_case)
 *
 * FIX-2026-01-19: Aligned with backend ReportMetadataDto
 * Fields match exactly what /teacher/reports/recent returns.
 *
 * @see apps/backend/src/modules/teacher/dto/teacher-reports.dto.ts
 */
export interface TeacherReport {
  /** Report ID (UUID) */
  id: string;
  /** Report name */
  report_name: string;
  /** Report type: 'individual' | 'classroom' | 'progress' | 'analytics' */
  report_type: string;
  /** Report format: 'pdf' | 'excel' | 'csv' */
  report_format: string;
  /** Number of students included in report */
  student_count: number;
  /** Period start date (ISO string or null) */
  period_start: string | null;
  /** Period end date (ISO string or null) */
  period_end: string | null;
  /** Generated at timestamp (ISO string) */
  generated_at: string;
  /** File size in bytes (optional) */
  file_size_bytes?: number | null;
}

/**
 * Report statistics
 *
 * FIX-2026-01-19: Aligned with backend ReportStatsDto
 * @see apps/backend/src/modules/teacher/dto/teacher-reports.dto.ts
 */
export interface ReportStats {
  /** Total number of reports generated by teacher */
  total_reports_generated: number;
  /** Last report generation date (ISO string or null) */
  last_generated_date: string | null;
  /** Most frequently used report format ('pdf' | 'excel' | 'csv' | null) */
  most_used_format: string | null;
  /** Average number of students per report */
  avg_students_per_report: number;
}

// ============================================================================
// API FUNCTIONS
// ============================================================================

/**
 * Generate a new insights report
 *
 * @description Generates a comprehensive report with student insights in PDF or Excel format.
 * Reports include risk analysis, recommendations, strengths/weaknesses, and predictions.
 * The report is persisted to storage and metadata is saved to the database.
 *
 * @param dto - Report generation options
 * @returns Promise<Blob> - The generated report file
 *
 * @example
 * ```typescript
 * const blob = await reportsApi.generateReport({
 *   type: 'student_insights',
 *   format: 'pdf',
 *   classroom_id: 'classroom-uuid'
 * });
 *
 * // Download the file
 * const url = URL.createObjectURL(blob);
 * const a = document.createElement('a');
 * a.href = url;
 * a.download = 'student-insights.pdf';
 * a.click();
 * ```
 */
export async function generateReport(dto: GenerateReportDto): Promise<{
  blob: Blob;
  metadata: {
    reportId: string;
    studentCount: number;
    generatedAt: string;
  };
}> {
  try {
    const response = await apiClient.post('/teacher/reports/generate', dto, {
      responseType: 'blob',
    });

    // Extract metadata from headers
    const metadata = {
      reportId: response.headers['x-report-id'] || '',
      studentCount: parseInt(response.headers['x-student-count'] || '0', 10),
      generatedAt: response.headers['x-generated-at'] || new Date().toISOString(),
    };

    return {
      blob: response.data,
      metadata,
    };
  } catch (error) {
    console.error('[ReportsAPI] Error generating report:', error);
    throw error;
  }
}

/**
 * Get list of recent reports
 *
 * @description Retrieve a list of recent reports generated by the teacher.
 * Results are ordered by generation date (most recent first).
 *
 * @param limit - Maximum number of reports to return (default: 10)
 * @returns Promise<TeacherReport[]> - List of recent reports
 *
 * @example
 * ```typescript
 * const reports = await reportsApi.getRecentReports(5);
 * reports.forEach(report => {
 *   console.log(`${report.reportName} - ${report.studentCount} students`);
 * });
 * ```
 */
export async function getRecentReports(limit: number = 10): Promise<TeacherReport[]> {
  try {
    const { data } = await apiClient.get<TeacherReport[]>('/teacher/reports/recent', {
      params: { limit },
    });
    return data;
  } catch (error) {
    console.error('[ReportsAPI] Error fetching recent reports:', error);
    throw error;
  }
}

/**
 * Get report statistics
 *
 * @description Retrieve statistics about reports generated by the teacher
 * including total counts, format breakdown, and students analyzed.
 *
 * @returns Promise<ReportStats> - Report statistics
 *
 * @example
 * ```typescript
 * const stats = await reportsApi.getReportStats();
 * console.log(`Total reports: ${stats.total_reports_generated}`);
 * console.log(`Most used format: ${stats.most_used_format}`);
 * console.log(`Avg students per report: ${stats.avg_students_per_report}`);
 * ```
 */
export async function getReportStats(): Promise<ReportStats> {
  try {
    const { data } = await apiClient.get<ReportStats>('/teacher/reports/stats');
    return data;
  } catch (error) {
    console.error('[ReportsAPI] Error fetching report stats:', error);
    throw error;
  }
}

/**
 * Download a previously generated report
 *
 * @description Download a report file. Validates teacher ownership.
 *
 * @param reportId - ID of the report to download
 * @returns Promise<Blob> - The report file
 *
 * @example
 * ```typescript
 * const blob = await reportsApi.downloadReport('report-uuid');
 *
 * // Create download link
 * const url = URL.createObjectURL(blob);
 * const a = document.createElement('a');
 * a.href = url;
 * a.download = 'report.pdf';
 * a.click();
 * ```
 */
export async function downloadReport(reportId: string): Promise<{
  blob: Blob;
  metadata: {
    reportId: string;
    teacherId: string;
    generatedAt: string;
    contentType: string;
  };
}> {
  try {
    const response = await apiClient.get(`/teacher/reports/${reportId}/download`, {
      responseType: 'blob',
    });

    const metadata = {
      reportId: response.headers['x-report-id'] || reportId,
      teacherId: response.headers['x-teacher-id'] || '',
      generatedAt: response.headers['x-generated-at'] || '',
      contentType: response.headers['content-type'] || 'application/octet-stream',
    };

    return {
      blob: response.data,
      metadata,
    };
  } catch (error) {
    console.error('[ReportsAPI] Error downloading report:', error);
    throw error;
  }
}

/**
 * Delete a report
 *
 * TASK-2026-01-18-015 Sprint 4.2: Delete report functionality
 *
 * @description Delete a report by ID. Validates teacher ownership.
 *
 * @param reportId - ID of the report to delete
 * @returns Promise<void>
 *
 * @example
 * ```typescript
 * await reportsApi.deleteReport('report-uuid');
 * ```
 */
export async function deleteReport(reportId: string): Promise<void> {
  try {
    await apiClient.delete(`/teacher/reports/${reportId}`);
  } catch (error) {
    console.error('[ReportsAPI] Error deleting report:', error);
    throw error;
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

/**
 * Reports API namespace
 *
 * @usage
 * ```typescript
 * import { reportsApi } from '@services/api/teacher/reportsApi';
 *
 * const result = await reportsApi.generateReport({ type: 'student_insights', format: 'pdf' });
 * const recent = await reportsApi.getRecentReports();
 * const stats = await reportsApi.getReportStats();
 * ```
 */
export const reportsApi = {
  generateReport,
  getRecentReports,
  getReportStats,
  downloadReport,
  deleteReport, // TASK-2026-01-18-015 Sprint 4.2
};

export default reportsApi;
