import { AnalisisMemesData } from './analisisMemesTypes';
import { DifficultyLevel } from '@shared/types/educational.types';

export const mockAnalisisMemesExercises: AnalisisMemesData[] = [{
  id: 'meme-001',
  title: 'Análisis de Meme: Marie Curie en la Cultura Popular',
  description: 'Analiza memes sobre Marie Curie identificando elementos clave como formato, mensaje, humor e ironía histórica',
  difficulty: DifficultyLevel.INTERMEDIATE,
  estimatedTime: 720,
  topic: 'Marie Curie - Análisis Visual',
  hints: [
    { id: 'h1', text: 'Busca referencias a la radioactividad', cost: 5 },
    { id: 'h2', text: 'Identifica el formato de meme utilizado', cost: 5 },
    { id: 'h3', text: 'Piensa en la ironía histórica del mensaje', cost: 10 },
  ],
  memeUrl: '/memes/marie-curie-glowing.svg',
  memeTitle: 'Drake Hotline Bling: Marie Curie',
  expectedAnnotations: [
    { id: 'a1', x: 425, y: 90, text: 'Texto superior: rechaza protección contra radiación', category: 'texto' },
    { id: 'a2', x: 425, y: 370, text: 'Texto inferior: aprueba experimentar sin protección', category: 'texto' },
    { id: 'a3', x: 140, y: 105, text: 'Formato Drake: panel de rechazo (arriba) y aprobación (abajo)', category: 'contexto' },
    { id: 'a4', x: 300, y: 250, text: 'Ironía: Curie murió por exposición a radiación', category: 'humor' },
    { id: 'a5', x: 530, y: 460, text: 'Símbolo radioactivo refuerza el tema', category: 'critica' },
  ],
  memes: [
    {
      id: 'meme1',
      imageUrl: '/memes/marie-curie-glowing.svg',
      format: 'Drake Hotline Bling',
      topText: 'Protección contra radiación',
      bottomText: 'Seguir experimentando sin protección',
      analysis: {
        mainMessage: 'Marie Curie no usaba protección contra radiación',
        humorType: 'Ironía histórica',
        culturalReference: 'Formato de meme popular Drake',
        historicalAccuracy: 'Alta - realmente no usaban protección adecuada',
        implication: 'Contraste entre conocimiento actual y pasado',
      },
    },
    {
      id: 'meme2',
      imageUrl: '/memes/expanding-brain-curie.svg',
      format: 'Expanding Brain',
      topText: 'Niveles de conocimiento sobre Marie Curie',
      analysis: {
        mainMessage: 'El conocimiento sobre Curie tiene muchos niveles de profundidad',
        humorType: 'Progresión cómica',
        culturalReference: 'Meme Expanding Brain con 4 niveles',
        historicalAccuracy: 'Alta - todos los datos son verificables',
        implication: 'Mientras más sabes, más fascinante es su historia',
      },
    },
    {
      id: 'meme3',
      imageUrl: '/memes/distracted-curie.svg',
      format: 'Distracted Boyfriend',
      topText: 'Marie Curie distraída por Radio',
      bottomText: 'Ignorando la Física Teórica',
      analysis: {
        mainMessage: 'Curie abandonó la física pura por la investigación de elementos radioactivos',
        humorType: 'Analogía visual',
        culturalReference: 'Meme Distracted Boyfriend adaptado a ciencia',
        historicalAccuracy: 'Media - simplificación de su carrera',
        implication: 'La pasión por descubrir nuevos elementos dominó su investigación',
      },
    },
    {
      id: 'meme4',
      imageUrl: '/memes/change-my-mind-curie.svg',
      format: 'Change My Mind',
      topText: 'Marie Curie es la científica más influyente de la historia',
      analysis: {
        mainMessage: 'Debate sobre la importancia de Marie Curie en la ciencia',
        humorType: 'Desafío retórico',
        culturalReference: 'Meme Change My Mind de Steven Crowder',
        historicalAccuracy: 'Subjetiva - opinión debatible pero bien fundamentada',
        implication: 'Invita a reflexionar sobre el impacto real de sus contribuciones',
      },
    },
    {
      id: 'meme5',
      imageUrl: '/memes/one-does-not-simply-curie.svg',
      format: 'One Does Not Simply',
      topText: 'No se puede simplemente ignorar la radioactividad',
      analysis: {
        mainMessage: 'La radioactividad es un fenómeno que no se puede ignorar una vez descubierto',
        humorType: 'Dramatización',
        culturalReference: 'Meme de Boromir (El Señor de los Anillos)',
        historicalAccuracy: 'Alta - la radioactividad transformó la ciencia moderna',
        implication: 'El descubrimiento de Curie cambió permanentemente la ciencia y la medicina',
      },
    },
    {
      id: 'meme6',
      imageUrl: '/memes/this-is-fine-curie.svg',
      format: 'This Is Fine',
      topText: 'Marie Curie en su laboratorio rodeada de materiales radioactivos',
      analysis: {
        mainMessage: 'Curie trabajaba con materiales peligrosos sin consciencia del riesgo',
        humorType: 'Humor negro / ironía situacional',
        culturalReference: 'Meme del perro en el fuego (KC Green)',
        historicalAccuracy: 'Alta - trabajaba sin protección en un laboratorio contaminado',
        implication: 'Reflexión sobre los riesgos que asumen los científicos pioneros',
      },
    },
  ],
  analysisQuestions: [
    '¿Cuál es el mensaje principal del meme?',
    '¿Qué formato de meme se utiliza?',
    '¿Es históricamente exacto?',
    '¿Por qué es gracioso/irónico?',
  ],
}];
