/**
 * Report Generation DTOs
 */

import { ApiProperty } from '@nestjs/swagger';
import { ReportFormat, ReportType } from '@shared/dto/reports/generate-report.dto';

export { GenerateReportDto, ReportFormat, ReportType } from '@shared/dto/reports/generate-report.dto';

/**
 * Report metadata for in-memory generated reports
 * FIX-2026-01-19: Renamed to avoid conflict with teacher-reports.dto.ts ReportMetadataDto
 * This DTO is for reports generated in memory (not persisted)
 * @see teacher-reports.dto.ts ReportMetadataDto for persisted reports
 */
export class GeneratedReportMetadataDto {
  @ApiProperty({ description: 'Report ID' })
    report_id!: string;

  @ApiProperty({ description: 'Report type', enum: ReportType })
    type!: ReportType;

  @ApiProperty({ description: 'Report format', enum: ReportFormat })
    format!: ReportFormat;

  @ApiProperty({ description: 'Generated at timestamp' })
    generated_at!: Date;

  @ApiProperty({ description: 'Generated by user ID' })
    generated_by!: string;

  @ApiProperty({ description: 'Number of students included' })
    student_count!: number;

  @ApiProperty({ description: 'File size in bytes' })
    file_size!: number;
}
