/**
 * Teacher Reports DTOs
 *
 * DTOs for teacher reports endpoints
 */

import { IsOptional, IsInt, Min, Max, IsString, IsEnum, IsDateString, IsNumber } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';

/**
 * DTO for creating a new teacher report record
 */
export class CreateTeacherReportDto {
  @ApiProperty({ description: 'Teacher ID (profile UUID)' })
  @IsString()
    teacherId!: string;

  @ApiProperty({ description: 'Tenant ID' })
  @IsString()
    tenantId!: string;

  @ApiProperty({ description: 'Report name' })
  @IsString()
    reportName!: string;

  @ApiProperty({
    description: 'Report type',
    enum: ['individual', 'classroom', 'progress', 'analytics'],
  })
  @IsEnum(['individual', 'classroom', 'progress', 'analytics'])
    reportType!: string;

  @ApiProperty({
    description: 'Report format',
    enum: ['pdf', 'excel', 'csv'],
  })
  @IsEnum(['pdf', 'excel', 'csv'])
    reportFormat!: string;

  @ApiProperty({ description: 'Classroom ID (optional)', required: false })
  @IsOptional()
  @IsString()
    classroomId?: string;

  @ApiProperty({ description: 'Number of students in report' })
  @IsInt()
  @Min(0)
    studentCount!: number;

  @ApiProperty({ description: 'Period start date', required: false })
  @IsOptional()
  @IsDateString()
    periodStart?: string;

  @ApiProperty({ description: 'Period end date', required: false })
  @IsOptional()
  @IsDateString()
    periodEnd?: string;

  @ApiProperty({ description: 'File path in storage' })
  @IsString()
    filePath!: string;

  @ApiProperty({ description: 'File size in bytes' })
  @IsNumber()
    fileSizeBytes!: number;
}

/**
 * Query DTO for GET /teacher/reports/recent endpoint
 */
export class GetRecentReportsQueryDto {
  @ApiProperty({
    description: 'Maximum number of reports to return',
    required: false,
    default: 10,
    minimum: 1,
    maximum: 50,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(50)
  @Type(() => Number)
    limit?: number = 10;
}

/**
 * Response DTO for report metadata
 *
 * FIX-2026-01-19: Added file_size_bytes field for Sprint 4.1 feature
 */
export class ReportMetadataDto {
  @ApiProperty({ description: 'Report ID (UUID)' })
    id!: string;

  @ApiProperty({ description: 'Report name' })
    report_name!: string;

  @ApiProperty({
    description: 'Report type',
    enum: ['individual', 'classroom', 'progress', 'analytics'],
  })
    report_type!: string;

  @ApiProperty({
    description: 'Report format',
    enum: ['pdf', 'excel', 'csv'],
  })
    report_format!: string;

  @ApiProperty({ description: 'Number of students included in report' })
    student_count!: number;

  @ApiProperty({ description: 'Period start date (ISO string or null)', nullable: true })
    period_start!: string | null;

  @ApiProperty({ description: 'Period end date (ISO string or null)', nullable: true })
    period_end!: string | null;

  @ApiProperty({ description: 'Generated at timestamp (ISO string)' })
    generated_at!: string;

  @ApiProperty({ description: 'File size in bytes (optional)', nullable: true, required: false })
    file_size_bytes?: number | null;
}

/**
 * Response DTO for report statistics
 */
export class ReportStatsDto {
  @ApiProperty({ description: 'Total number of reports generated by teacher' })
    total_reports_generated!: number;

  @ApiProperty({ description: 'Last report generation date (ISO string or null)', nullable: true })
    last_generated_date!: string | null;

  @ApiProperty({ description: 'Most frequently used report format', nullable: true })
    most_used_format!: string | null;

  @ApiProperty({ description: 'Average number of students per report' })
    avg_students_per_report!: number;
}
