/**
 * Teacher Reports DTOs
 *
 * DTOs for teacher reports endpoints
 */

import { IsOptional, IsInt, Min, Max } from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';

/**
 * Query DTO for GET /teacher/reports/recent endpoint
 */
export class GetRecentReportsQueryDto {
  @ApiProperty({
    description: 'Maximum number of reports to return',
    required: false,
    default: 10,
    minimum: 1,
    maximum: 50,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(50)
  @Type(() => Number)
  limit?: number = 10;
}

/**
 * Response DTO for report metadata
 */
export class ReportMetadataDto {
  @ApiProperty({ description: 'Report ID (UUID)' })
  id!: string;

  @ApiProperty({ description: 'Report name' })
  report_name!: string;

  @ApiProperty({
    description: 'Report type',
    enum: ['individual', 'classroom', 'progress', 'analytics'],
  })
  report_type!: string;

  @ApiProperty({
    description: 'Report format',
    enum: ['pdf', 'excel', 'csv'],
  })
  report_format!: string;

  @ApiProperty({ description: 'Number of students included in report' })
  student_count!: number;

  @ApiProperty({ description: 'Period start date (ISO string or null)', nullable: true })
  period_start!: string | null;

  @ApiProperty({ description: 'Period end date (ISO string or null)', nullable: true })
  period_end!: string | null;

  @ApiProperty({ description: 'Generated at timestamp (ISO string)' })
  generated_at!: string;
}

/**
 * Response DTO for report statistics
 */
export class ReportStatsDto {
  @ApiProperty({ description: 'Total number of reports generated by teacher' })
  total_reports_generated!: number;

  @ApiProperty({ description: 'Last report generation date (ISO string or null)', nullable: true })
  last_generated_date!: string | null;

  @ApiProperty({ description: 'Most frequently used report format', nullable: true })
  most_used_format!: string | null;

  @ApiProperty({ description: 'Average number of students per report' })
  avg_students_per_report!: number;
}
